### ISSUE TITLE
Celluloid < 0.14

### ISSUE THREAD

**Issue by bryanrite** [adhearsion/att_speech#4]
Any reason we should be pinned to celluloid < 0.14?

Seems to work on 0.15.2.

**Comment by bryanrite** [comment]
My mistake, there is a spec failure, looking into it.

**Comment by bryanrite** [comment]
The async method in celluloid has changed from bang to `.async`, but it doesn't take blocks, so the specs with futures and blocks fail:

`AttSpeech non-blocking call with a block should allow us to use a future to process an audio file and pass a block`

**Comment by bklang** [comment]
Addressed in #7

**Comment by bryanrite** [comment]
@bklang You sir, are a gentleman and A scholar.
